baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "heshotheme"


[[menu.main]]
name               	= "Home"
weight             	= -202
identifier         	= "home"
url                	= "/index.html/"

[[menu.main]]
name               	= "Contact"
weight             	= -201
identifier         	= "contact"
url                	= "/contact/"

[[menu.main]]
name               	= "Farver"
weight             	= -201
identifier         	= "farver"
url                	= "/farver/"

[[menu.main]]
name               	= "Typografi"
weight             	= -201
identifier         	= "typografi"
url                	= "/typografi/"

[[menu.main]]
name               	= "Grafik"
weight             	= -201
identifier         	= "grafik"
url                	= "/grafik/"


