baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "heshotheme"


[[menu.main]]
name               	= "Farver"
weight             	= -201
identifier         	= "farver"
url                	= "/farver/"

[[menu.main]]
name               	= "Typografi"
weight             	= -101
identifier         	= "typografi"
url                	= "/typografi/"


[[menu.main]]
name               	= "Om"
weight             	= -101
identifier         	= "om"
url                	= "/om/"
