baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "heshotheme"


[[menu.main]]
name               	= "Home"
weight             	= -202
identifier         	= "home"
url                	= "/index.html/"

[[menu.main]]
name               	= "Contact"
weight             	= -201
identifier         	= "contact"
url                	= "/contact/"

[[menu.main]]
name               	= "Dokumentation"
weight             	= -201
identifier         	= "dokumentation"
url                	= "/dokumentation/"


